// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package chain

import (
	context "context"

	types "github.com/coinbase/rosetta-sdk-go/types"
	mock "github.com/stretchr/testify/mock"
)

// NetworkBackend is an autogenerated mock type for the NetworkBackend type
type NetworkBackend struct {
	mock.Mock
}

// NetworkIdentifier provides a mock function with given fields:
func (_m *NetworkBackend) NetworkIdentifier() *types.NetworkIdentifier {
	ret := _m.Called()

	var r0 *types.NetworkIdentifier
	if rf, ok := ret.Get(0).(func() *types.NetworkIdentifier); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.NetworkIdentifier)
		}
	}

	return r0
}

// NetworkOptions provides a mock function with given fields: ctx, request
func (_m *NetworkBackend) NetworkOptions(ctx context.Context, request *types.NetworkRequest) (*types.NetworkOptionsResponse, *types.Error) {
	ret := _m.Called(ctx, request)

	var r0 *types.NetworkOptionsResponse
	if rf, ok := ret.Get(0).(func(context.Context, *types.NetworkRequest) *types.NetworkOptionsResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.NetworkOptionsResponse)
		}
	}

	var r1 *types.Error
	if rf, ok := ret.Get(1).(func(context.Context, *types.NetworkRequest) *types.Error); ok {
		r1 = rf(ctx, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*types.Error)
		}
	}

	return r0, r1
}

// NetworkStatus provides a mock function with given fields: ctx, request
func (_m *NetworkBackend) NetworkStatus(ctx context.Context, request *types.NetworkRequest) (*types.NetworkStatusResponse, *types.Error) {
	ret := _m.Called(ctx, request)

	var r0 *types.NetworkStatusResponse
	if rf, ok := ret.Get(0).(func(context.Context, *types.NetworkRequest) *types.NetworkStatusResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.NetworkStatusResponse)
		}
	}

	var r1 *types.Error
	if rf, ok := ret.Get(1).(func(context.Context, *types.NetworkRequest) *types.Error); ok {
		r1 = rf(ctx, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*types.Error)
		}
	}

	return r0, r1
}
