// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package chain

import (
	common "github.com/ava-labs/avalanche-rosetta/service/backend/common"
	mock "github.com/stretchr/testify/mock"

	types "github.com/coinbase/rosetta-sdk-go/types"
)

// TxParser is an autogenerated mock type for the TxParser type
type TxParser struct {
	mock.Mock
}

// ParseTx provides a mock function with given fields: tx, isConstruction
func (_m *TxParser) ParseTx(tx common.AvaxTx, isConstruction bool) ([]*types.Operation, error) {
	ret := _m.Called(tx, isConstruction)

	var r0 []*types.Operation
	if rf, ok := ret.Get(0).(func(common.AvaxTx, bool) []*types.Operation); ok {
		r0 = rf(tx, isConstruction)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.Operation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(common.AvaxTx, bool) error); ok {
		r1 = rf(tx, isConstruction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
